[package]
name = "tauri-plugin-mixpanel"
version = "0.1.0"
authors = [ "You" ]
description = "Tauri plugin for Mixpanel analytics"
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-mixpanel"

[dependencies]
tauri = { version = "2.5.0" }
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.32", features = ["sync"] }
log = "0.4"
mixpanel-rs = { path = "../../" }

[build-dependencies]
tauri-plugin = { version = "2.2.0", features = ["build"] }
